export type AppModule = {
  label: string;
  href: string;
  group?: string;
  children?: { label: string; href: string }[];
  /** Render as a filled call-to-action button in the sidebar (e.g. Pay Assessments). */
  accent?: boolean;
};

export const appModules: AppModule[] = [
  { label: 'Dashboard', href: '/dashboard', group: 'Workspace' },
  { label: 'AI Assistant', href: '/assistant', group: 'Workspace' },
  { label: 'Reminders', href: '/reminders', group: 'Workspace' },
  { label: 'Calendar', href: '/calendar', group: 'Workspace' },
  { label: 'Meetings', href: '/meetings', group: 'Workspace' },
  {
    label: 'Associations',
    href: '/associations',
    group: 'Portfolio',
    children: [
      { label: 'Association directory', href: '/associations' },
      { label: 'New association', href: '/associations/new' },
      { label: 'Import homeowners & units', href: '/owners/import' },
      { label: 'Units', href: '/units' },
      { label: 'Parking', href: '/parking' },
      { label: 'Amenities', href: '/amenities' },
      { label: 'Lock boxes & keys', href: '/lock-boxes' },
    ],
  },
  {
    label: 'People',
    href: '/owners',
    group: 'Portfolio',
    children: [
      { label: 'Homeowner directory', href: '/owners' },
      { label: 'New homeowner', href: '/owners/new' },
      { label: 'Portal activations', href: '/owners/activations' },
      { label: 'Owner forms', href: '/owners/forms' },
      { label: 'Management agreements', href: '/owners/management-agreements' },
      { label: 'Send statements', href: '/statements/send' },
    ],
  },
  {
    label: 'Vendors',
    href: '/vendors',
    group: 'Portfolio',
    children: [
      { label: 'Vendor directory', href: '/vendors' },
      { label: 'New vendor', href: '/vendors/new' },
      { label: 'Compliance', href: '/vendors/compliance' },
      { label: 'W-9 collection', href: '/vendors/w9' },
      { label: 'ACH preferences', href: '/vendors/ach' },
    ],
  },
  {
    label: 'Accounting',
    href: '/accounting',
    group: 'Finance',
    children: [
      { label: 'Accounting overview', href: '/accounting' },
      { label: 'Command Center', href: '/command-center' },
      { label: 'Receivables', href: '/charges' },
      { label: 'Charge categories', href: '/charge-categories' },
      { label: 'Delinquency ladder', href: '/delinquencies' },
      { label: 'Payables', href: '/bills' },
      { label: 'Check run', href: '/bills/check-run' },
      { label: 'Bank accounts', href: '/bank-accounts' },
      { label: 'Bank reconciliation', href: '/bank-accounts/reconcile' },
      { label: 'Bank activity', href: '/bank-accounts/activity' },
      { label: 'Bank transfers', href: '/bank-transfers' },
      { label: 'Journal entries', href: '/journal-entries' },
      { label: 'GL accounts', href: '/gl-accounts' },
      { label: 'Accounting periods', href: '/accounting-periods' },
      { label: 'Budget', href: '/budget' },
      { label: 'Budget vs actuals', href: '/budget-vs-actuals' },
      { label: 'Capital & reserves', href: '/capital-reserves' },
      { label: 'Financial diagnostics', href: '/diagnostics' },
      { label: '1099 reporting', href: '/accounting/1099' },
    ],
  },
  {
    label: 'Reports',
    href: '/reports',
    group: 'Insights',
    children: [
      { label: 'Report catalog', href: '/reports' },
      { label: 'Report builder', href: '/reports/builder' },
      { label: 'Scheduled reports', href: '/scheduled-reports' },
      { label: 'Monthly board package', href: '/reports/monthly-package' },
      { label: 'Bulk association reports', href: '/reports/bulk-association' },
      { label: 'Run history', href: '/reports/runs' },
      { label: 'Metrics', href: '/metrics' },
    ],
  },
  {
    label: 'Violations',
    href: '/violations',
    group: 'Operations',
    children: [
      { label: 'Violation queue', href: '/violations' },
      { label: 'New violation', href: '/violations/new' },
      { label: 'Field capture', href: '/violations/field' },
      { label: 'Compliance overview', href: '/compliance' },
      { label: 'Architectural reviews', href: '/architectural-reviews' },
      { label: 'Insurance', href: '/insurance' },
    ],
  },
  {
    label: 'Maintenance',
    href: '/maintenance',
    group: 'Operations',
    children: [
      { label: 'Maintenance overview', href: '/maintenance' },
      { label: 'Work orders', href: '/work-orders' },
      { label: 'Recurring work orders', href: '/recurring-work-orders' },
      { label: 'Inspections', href: '/inspections' },
      { label: 'Projects', href: '/projects' },
      { label: 'Purchase orders', href: '/purchase-orders' },
      { label: 'Inventory', href: '/inventory' },
      { label: 'Fixed assets', href: '/fixed-assets' },
      { label: 'Preventive templates', href: '/maintenance/templates' },
      { label: 'Maintenance communications', href: '/maintenance/communications' },
    ],
  },
  {
    label: 'Documents',
    href: '/documents',
    group: 'Communication',
    children: [
      { label: 'Document library', href: '/documents' },
      { label: 'Generate document', href: '/documents/generate' },
      { label: 'Templates', href: '/documents?tab=templates' },
      { label: 'Notices', href: '/documents?tab=notices' },
      { label: 'Forms', href: '/forms' },
    ],
  },
  {
    label: 'Communication',
    href: '/communication-center',
    group: 'Communication',
    children: [
      { label: 'Communication Center', href: '/communication-center' },
      { label: 'Unified inbox', href: '/inbox' },
      { label: 'Compose email', href: '/send-email' },
      { label: 'SMS console', href: '/sms' },
      { label: 'SMS templates', href: '/sms/templates' },
      { label: 'SMS opt-ins', href: '/sms/opt-ins' },
      { label: 'Letters', href: '/letters' },
      { label: 'Physical mail', href: '/letters/mail' },
      { label: 'Surveys', href: '/surveys' },
    ],
  },
  {
    label: 'Automation Center',
    href: '/automation-center',
    group: 'Administration',
    children: [
      { label: 'Automation overview', href: '/automation-center' },
      { label: 'Flows', href: '/automation-center/flows' },
      { label: 'New flow', href: '/automation-center/flows/new' },
    ],
  },
  {
    label: 'Settings',
    href: '/settings',
    group: 'Administration',
    children: [
      { label: 'Portfolio & team', href: '/settings' },
      { label: 'Branding', href: '/settings/branding' },
      { label: 'AI configuration', href: '/settings/ai' },
      { label: 'Developer Hub', href: '/settings/developer' },
    ],
  },
];
