// Role-specific navigation for the unified Sidebar. One design, six doors.
import type { AppModule } from './modules';

export const boardModules: AppModule[] = [
  { label: 'Dashboard', href: '/board' },
  { label: 'AI Board Assistant', href: '/board/assistant' },
  { label: 'Meetings', href: '/board/meetings' },
  { label: 'Approvals', href: '/board/approvals' },
  { label: 'Financials', href: '/board/financials' },
  { label: 'Budget vs Actual', href: '/board/budget' },
  { label: 'Delinquencies', href: '/board/delinquencies' },
  { label: 'Homeowners', href: '/board/owners' },
  { label: 'Violations', href: '/board/violations' },
  { label: 'Architectural Reviews', href: '/board/architectural-reviews' },
  { label: 'Projects', href: '/board/projects' },
  { label: 'Work Orders', href: '/board/work-orders' },
  { label: 'Vendors', href: '/board/vendors' },
  { label: 'Compliance', href: '/board/compliance' },
  { label: 'Insurance', href: '/board/insurance' },
  { label: 'Calendar', href: '/board/calendar' },
  { label: 'Documents', href: '/board/documents' },
  { label: 'Reports', href: '/board/reports' },
  { label: 'Communications', href: '/board/communications' },
];

export const ownerModules: AppModule[] = [
  { label: 'Dashboard', href: '/portal' },
  { label: 'AI Assistant', href: '/portal/assistant' },
  { label: 'My Home', href: '/portal/home' },
  { label: 'My Account', href: '/portal/account' },
  { label: 'How to Pay', href: '/portal/pay' },
  { label: 'Work Orders', href: '/portal/work-orders' },
  { label: 'Violations', href: '/portal/violations' },
  { label: 'Architectural Requests', href: '/portal/architectural' },
  { label: 'Amenities', href: '/portal/amenities' },
  { label: 'Hearings', href: '/portal/hearings' },
  { label: 'Communications', href: '/portal/communications' },
  { label: 'Calendar', href: '/portal/calendar' },
  { label: 'Meetings', href: '/portal/meetings' },
  { label: 'Documents', href: '/portal/documents' },
  { label: 'Insurance', href: '/portal/insurance' },
  { label: 'Vehicles', href: '/portal/vehicles' },
  { label: 'Lease', href: '/portal/lease' },
  { label: 'Emergency Info', href: '/portal/emergency' },
  { label: 'Profile', href: '/portal/profile' },
];

export const companyAdminModules: AppModule[] = [
  { label: 'Overview', href: '/company-admin/overview' },
  { label: 'AI Command Center', href: '/company-admin/insights' },
  { label: 'Associations', href: '/company-admin/associations' },
  { label: 'Managers', href: '/company-admin/managers' },
  { label: 'Performance', href: '/company-admin/performance' },
  { label: 'Portfolio Health', href: '/company-admin/portfolio-health' },
  { label: 'Financials', href: '/company-admin/financials' },
  { label: 'Command Center', href: '/command-center' },
  { label: 'Work Orders', href: '/company-admin/work-orders' },
  { label: 'Violations', href: '/company-admin/violations' },
  { label: 'Architectural Reviews', href: '/company-admin/architectural-reviews' },
  { label: 'Compliance', href: '/company-admin/compliance' },
  { label: 'Maintenance', href: '/company-admin/maintenance' },
  { label: 'Owners', href: '/company-admin/owners' },
  { label: 'Vendors', href: '/company-admin/vendors' },
  { label: 'Documents', href: '/company-admin/documents' },
  { label: 'Billing & Doors', href: '/company-admin/billing' },
  { label: 'Revenue', href: '/company-admin/revenue' },
  { label: 'Communications', href: '/company-admin/communications' },
  { label: 'Platform Requests', href: '/company-admin/platform-requests' },
  { label: 'Audit Logs', href: '/company-admin/audit-logs' },
  { label: 'Settings', href: '/company-admin/settings' },
];

export const platformOperatorModules: AppModule[] = [
  { label: 'Overview', href: '/platform-operator' },
  { label: 'Platform Intelligence', href: '/platform-operator/insights' },
  { label: 'Companies', href: '/platform-operator/companies' },
  { label: 'Invitations', href: '/platform-operator/invitations' },
  { label: 'Users', href: '/platform-operator/users' },
  { label: 'Operators', href: '/platform-operator/operators' },
  { label: 'Billing', href: '/platform-operator/billing' },
  { label: 'Door Usage', href: '/platform-operator/door-usage' },
  { label: 'Revenue', href: '/platform-operator/revenue' },
  { label: 'Association Health', href: '/platform-operator/association-health' },
  { label: 'Announcements', href: '/platform-operator/announcements' },
  { label: 'Communications', href: '/platform-operator/communications' },
  { label: 'Support Requests', href: '/platform-operator/support' },
  { label: 'System Monitor', href: '/platform-operator/system' },
  { label: 'Security Center', href: '/platform-operator/security' },
  { label: 'Audit Logs', href: '/platform-operator/audit-logs' },
];

export const vendorModules: AppModule[] = [
  { label: 'Dashboard', href: '/vendor' },
  { label: 'AI Assistant', href: '/vendor/assistant' },
  { label: 'Work Orders', href: '/vendor/work-orders' },
  { label: 'Schedule', href: '/vendor/schedule' },
  { label: 'Properties', href: '/vendor/properties' },
  { label: 'Payments', href: '/vendor/payments' },
  { label: 'Performance', href: '/vendor/performance' },
  { label: 'Compliance', href: '/vendor/compliance' },
  { label: 'Profile', href: '/vendor/profile' },
];
