-- Hardening from the security review of 20261007030000:
--
-- 1. user_invitations.token must be exactly 64 lowercase hex characters —
--    what every real path produces (the column default and
--    generate_invite_token()). Staff can insert or update invitation rows
--    directly (user_invitations_staff_insert / _admin_all) and could choose
--    the token: markup that breaks out of the email link, or a well-formed but
--    guessable value. The exact shape refuses markup; a format can't prove a
--    token is random, so rows written through the API (authenticated/anon)
--    always get a server-generated token on insert and can't change it on
--    update (trigger below). Server-side paths (service role, SECURITY
--    DEFINER functions) are unchanged. Production had 0 invitation rows when
--    this was written, so the check is validated immediately; guarded so a
--    re-run doesn't fail.
--
-- 2. public.html_escape also escapes the single quote (&#39;), so its output is
--    safe inside single-quoted attributes too. All callers build HTML email
--    bodies (dues reminders, calendar notices, owner messages, invitations);
--    the text conversion in lib/email/queue.ts already decodes &#39;.
--    Signature, language, volatility, search_path and grants are unchanged.
--
-- Additive only: no DROP, no DELETE.

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'user_invitations_token_format'
      and conrelid = 'public.user_invitations'::regclass
  ) then
    alter table public.user_invitations
      add constraint user_invitations_token_format
      check (token ~ '^[0-9a-f]{64}$');
  end if;
end $$;

-- Runs as the caller (not SECURITY DEFINER) so current_user is the API role;
-- the token is generated the same way as the column default.
create or replace function public.user_invitations_server_token()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if current_user in ('authenticated', 'anon') then
    if tg_op = 'INSERT' then
      new.token := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
    elsif new.token is distinct from old.token then
      raise exception 'Invitation tokens are generated by the server and cannot be changed';
    end if;
  end if;
  return new;
end;
$$;

create or replace trigger user_invitations_server_token
  before insert or update of token on public.user_invitations
  for each row execute function public.user_invitations_server_token();

create or replace function public.html_escape(p text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select replace(replace(replace(replace(replace(coalesce(p, ''),
    '&', '&amp;'), '<', '&lt;'), '>', '&gt;'), '"', '&quot;'), '''', '&#39;');
$$;
