-- Report exports are generated by the service-role worker and exposed only
-- through short-lived signed URLs. Keep the bucket private in every
-- environment; no authenticated storage.objects policy is required.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'reports',
  'reports',
  false,
  20971520,
  array['application/pdf', 'text/csv', 'application/json']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

