-- Expand the report catalog to match the operations Reports workspace.
-- These are queued report definitions unless a live view is implemented.

with catalog(slug, name, category, description) as (
  values
    -- Accounting reports
    ('account_totals', 'Account Totals', 'accounting', 'Totals by general ledger account for the selected period.'),
    ('annual_budget_comparative', 'Annual Budget Comparative', 'accounting', 'Annual budget comparison by account and association.'),
    ('balance_sheet', 'Balance Sheet', 'accounting', 'Assets, liabilities, and fund balances as of a selected date.'),
    ('balance_sheet_comparative', 'Balance Sheet - Comparative', 'accounting', 'Balance sheet compared across periods.'),
    ('balance_sheet_property_comparison', 'Balance Sheet - Property Comparison', 'accounting', 'Balance sheet compared across associations or properties.'),
    ('bank_account_activity', 'Bank Account Activity', 'accounting', 'Bank activity by account with debits, credits, and running balances.'),
    ('bank_account_reconciliation', 'Bank Account Reconciliation', 'accounting', 'Reconciliation detail for a selected bank account.'),
    ('bank_reconciliation', 'Bank Reconciliation', 'accounting', 'Bank reconciliation summary and exceptions.'),
    ('budget_vs_actual', 'Budget vs Actual', 'accounting', 'Budgeted amounts compared with actual activity.'),
    ('cash_flow', 'Cash Flow Statement', 'accounting', 'Cash inflows and outflows by operating activity.'),
    ('cash_flow_12_month', 'Cash Flow - 12 Month', 'accounting', 'Trailing 12 month cash flow trend.'),
    ('cash_flow_detail', 'Cash Flow Detail', 'accounting', 'Transaction detail behind cash flow totals.'),
    ('cash_flow_property_comparison', 'Cash Flow - Property Comparison', 'accounting', 'Cash flow compared across associations or properties.'),
    ('expense_distribution', 'Expense Distribution', 'accounting', 'Expense activity distributed by account, property, and vendor.'),
    ('fund_balance_sheet', 'Fund Balance Sheet', 'accounting', 'Balance sheet grouped by operating, reserve, and special funds.'),
    ('general_account', 'General Account', 'accounting', 'General account summary for selected accounts.'),
    ('general_ledger', 'General Ledger', 'accounting', 'Full ledger detail by account.'),
    ('income_register', 'Income Register', 'accounting', 'Income transactions for a selected period.'),
    ('income_statement', 'Income Statement', 'accounting', 'Income and expenses for a selected period.'),
    ('income_statement_12_month', 'Income Statement - 12 Month', 'accounting', 'Trailing 12 month income statement trend.'),
    ('income_statement_comparative', 'Income Statement - Comparative', 'accounting', 'Income statement compared across periods.'),
    ('income_statement_property_comparison', 'Income Statement - Property Comparison', 'accounting', 'Income statement compared across associations or properties.'),
    ('loan_statement', 'Loan Statement', 'accounting', 'Loan balances, payments, and interest activity.'),
    ('management_fee_summary', 'Management Fee Summary', 'accounting', 'Management fee totals by association, owner, and period.'),
    ('reserve_fund_analysis', 'Reserve Fund Analysis', 'accounting', 'Reserve fund balances, contributions, and spending.'),
    ('trial_balance', 'Trial Balance', 'accounting', 'Debit and credit balances by general ledger account.'),
    ('trial_balance_property', 'Trial Balance Property', 'accounting', 'Trial balance broken out by association or property.'),
    ('trust_account_balance', 'Trust Account Balance', 'accounting', 'Trust account balance summary.'),
    ('trust_account_detail', 'Trust Account Detail', 'accounting', 'Trust account transaction detail.'),

    -- Association reports
    ('architectural_review', 'Architectural Review', 'association', 'Architectural review requests and decisions.'),
    ('association_vendor', 'Association Vendor', 'association', 'Vendors assigned to each association.'),
    ('board_directory', 'Board Directory', 'association', 'Board member roster and contact details.'),
    ('board_packet', 'Board Packet', 'association', 'Board packet report bundle.'),
    ('board_rollup', 'Board Rollup', 'association', 'Board-level summary across association operations.'),
    ('board_work_orders', 'Board Work Orders', 'association', 'Work orders visible to the board.'),
    ('delinquency', 'Delinquency Report', 'association', 'Delinquent balances by owner or unit.'),
    ('delinquency_summary', 'Delinquency Summary', 'association', 'Summary of delinquent balances and counts.'),
    ('dues_roll', 'Dues Roll', 'association', 'Recurring dues and assessments by unit.'),
    ('email_opt_out', 'Email Opt Out', 'association', 'Owners and residents opted out of email delivery.'),
    ('homeowner_balance', 'Homeowner Balance', 'association', 'Current homeowner balances by unit.'),
    ('homeowner_directory', 'Homeowner Directory', 'association', 'Homeowner contact directory.'),
    ('homeowner_ledger', 'Homeowner Ledger', 'association', 'Homeowner ledger activity and balances.'),
    ('homeowner_prepaid', 'Homeowner Prepaid', 'association', 'Homeowner prepaid balances and credits.'),
    ('homeowner_vehicle_info', 'Homeowner Vehicle Info', 'association', 'Vehicle records for homeowners and residents.'),
    ('homeowner_violations', 'Homeowner Violations', 'association', 'Open and historical homeowner violations.'),
    ('insurance_expiration_dates', 'Insurance Expiration Dates', 'association', 'Association and vendor insurance expiration tracking.'),
    ('lease_expirations', 'Lease Expirations', 'association', 'Expiring leases by association and unit.'),
    ('mailing_labels', 'Mailing Labels', 'association', 'Mailing label export for owners and residents.'),
    ('owner_directory', 'Owner Directory', 'people', 'Owner contact directory.'),
    ('owner_ledger', 'Owner Ledger', 'association', 'Owner ledger activity and balances.'),
    ('resident_directory', 'Resident Directory', 'association', 'Resident contact directory.'),
    ('tenant_directory', 'Tenant Directory', 'association', 'Tenant contact directory.'),
    ('vehicle_info', 'Vehicle Info', 'association', 'Vehicle information by owner, resident, and unit.'),

    -- Diagnostic reports
    ('application_settings', 'Application Settings', 'compliance', 'Portfolio and association application settings.'),
    ('data_diagnostics_summary', 'Data Diagnostics Summary', 'compliance', 'Data quality warnings and operational diagnostics.'),
    ('email_delivery_errors', 'Email Delivery Errors', 'compliance', 'Email delivery failures and bounce reasons.'),
    ('import_validation', 'Import Validation', 'compliance', 'Import validation errors and warnings.'),
    ('inspection_reasons', 'Inspection Reasons', 'compliance', 'Inspection reason usage and setup.'),
    ('lease_file_policy_comparison', 'Lease File Policy Comparison', 'compliance', 'Lease file policy comparison by association.'),
    ('login_audit', 'Login Audit', 'compliance', 'User login and access activity.'),
    ('residents_check_fee_coverage', 'Residents Check Fee Coverage', 'compliance', 'Resident check fee coverage settings and exceptions.'),
    ('user_roles_permissions', 'User Roles and Permissions', 'compliance', 'User roles, permissions, and access assignments.'),
    ('violation_log', 'Violation Log', 'compliance', 'Violation history and status tracking.'),

    -- Maintenance reports
    ('inspection_detail', 'Inspection Detail', 'maintenance', 'Inspection detail by association, unit, and status.'),
    ('maintenance_history', 'Maintenance History', 'maintenance', 'Maintenance history across work orders and service requests.'),
    ('open_work_orders', 'Open Work Orders', 'maintenance', 'Open work orders by association, unit, vendor, and priority.'),
    ('project_budget_detail', 'Project Budget Detail', 'maintenance', 'Project budget detail and spending.'),
    ('project_directory', 'Project Directory', 'maintenance', 'Project directory and status listing.'),
    ('purchase_order', 'Purchase Order', 'maintenance', 'Purchase order listing and status.'),
    ('purchase_order_detail', 'Purchase Order Detail', 'maintenance', 'Purchase order line item detail.'),
    ('recurring_work_orders', 'Recurring Work Orders', 'maintenance', 'Recurring work order templates and schedules.'),
    ('task_list', 'Task List', 'maintenance', 'Maintenance task list by assignee and due date.'),
    ('vendor_directory', 'Vendor Directory', 'people', 'Vendor contact directory.'),
    ('vendor_performance', 'Vendor Performance', 'maintenance', 'Vendor performance metrics and work order history.'),
    ('work_order_bill_detail', 'Work Order Bill Detail', 'maintenance', 'Bills associated with work orders.'),
    ('work_order_labor_summary', 'Work Order Labor Summary', 'maintenance', 'Labor summary by work order and vendor.'),
    ('work_order_report', 'Work Order Report', 'maintenance', 'Work order detail and status report.'),

    -- Property and unit reports
    ('amenities_assigned', 'Amenities Assigned', 'property_unit', 'Amenities assigned to units and associations.'),
    ('association_log', 'Association Log', 'property_unit', 'Association activity log.'),
    ('building_and_unit', 'Building And Unit', 'property_unit', 'Building and unit inventory.'),
    ('building_list', 'Building List', 'property_unit', 'Building directory by association.'),
    ('inventory_ledger', 'Inventory Ledger', 'property_unit', 'Inventory activity and balances.'),
    ('keys', 'Keys', 'property_unit', 'Key assignments and holders.'),
    ('parking_spaces', 'Parking Spaces', 'property_unit', 'Parking space assignments and availability.'),
    ('property_directory', 'Property Directory', 'property_unit', 'Property and association directory.'),
    ('property_inspection', 'Property Inspection', 'property_unit', 'Property inspection summary and findings.'),
    ('rentable_units', 'Rentable Units', 'property_unit', 'Rentable unit listing and status.'),
    ('unit_availability', 'Unit Availability', 'property_unit', 'Available and unavailable units.'),
    ('unit_directory', 'Unit Directory', 'property_unit', 'Unit directory by association and building.'),
    ('unit_inspection', 'Unit Inspection', 'property_unit', 'Unit inspection summary and findings.'),
    ('unit_make_ready', 'Unit Make Ready', 'property_unit', 'Unit make-ready tasks and status.'),
    ('unit_turn_report', 'Unit Turn Report', 'property_unit', 'Unit turn status and timing.'),
    ('units_by_owner', 'Units By Owner', 'property_unit', 'Units grouped by owner.'),

    -- Tax reports
    ('owner_1099_detail', 'Owner 1099 Detail', 'accounting', 'Owner 1099 transaction detail.'),
    ('owner_1099_summary', 'Owner 1099 Summary', 'accounting', 'Owner 1099 summary totals.'),
    ('owner_tax_detail', 'Owner Tax Detail', 'accounting', 'Owner tax detail for reporting.'),
    ('owner_tax_summary', 'Owner Tax Summary', 'accounting', 'Owner tax summary totals.'),
    ('vendor_1099_detail', 'Vendor 1099 Detail', 'accounting', 'Vendor 1099 transaction detail.'),
    ('vendor_1099_summary', 'Vendor 1099 Summary', 'accounting', 'Vendor 1099 summary totals.'),
    ('vendor_tax_detail', 'Vendor Tax Detail', 'accounting', 'Vendor tax detail for reporting.'),
    ('vendor_tax_summary', 'Vendor Tax Summary', 'accounting', 'Vendor tax summary totals.'),

    -- Transaction reports
    ('ap_aging', 'A/P Aging', 'accounting', 'Aging for unpaid payable bills.'),
    ('ap_transaction_summary', 'A/P Transaction Summary', 'accounting', 'Accounts payable transaction summary.'),
    ('ar_aging', 'A/R Aging', 'accounting', 'Aging for receivable balances.'),
    ('aged_payables_summary', 'Aged Payables Summary', 'accounting', 'Summary of aged payable balances.'),
    ('bill_detail', 'Bill Detail', 'accounting', 'Payable bill detail.'),
    ('charge_detail', 'Charge Detail', 'accounting', 'Charge detail by unit and category.'),
    ('charge_register', 'Charge Register', 'accounting', 'Register of charges posted.'),
    ('check_register', 'Check Register', 'accounting', 'Checks written by bank account.'),
    ('check_register_detail', 'Check Register Detail', 'accounting', 'Detailed checks written by bank account.'),
    ('deposit_register', 'Deposit Register', 'accounting', 'Deposits and owner payments by bank account.'),
    ('expense_register', 'Expense Register', 'accounting', 'Expense transaction register.'),
    ('invoice_register', 'Invoice Register', 'accounting', 'Invoice and assessment register.'),
    ('journal_entry_register', 'Journal Entry Register', 'accounting', 'Journal entry transaction register.'),
    ('payment_register', 'Payment Register', 'accounting', 'Payment transaction register.'),
    ('refund_register', 'Refund Register', 'accounting', 'Refund transaction register.'),
    ('transfer_register', 'Transfer Register', 'accounting', 'Bank and ledger transfer register.'),
    ('unapplied_receipts', 'Unapplied Receipts', 'accounting', 'Receipts not fully applied to charges.'),
    ('unpaid_balances_by_month', 'Unpaid Balances by Month', 'accounting', 'Unpaid balances trended by month.'),
    ('vendor_payment_register', 'Vendor Payment Register', 'accounting', 'Vendor payments by date and bank account.'),
    ('voided_check_register', 'Voided Check Register', 'accounting', 'Voided checks and related payment details.'),

    -- Communication reports
    ('letter_history', 'Letter History', 'communication', 'Letters generated and sent.'),
    ('market_metrics', 'Market Metrics', 'communication', 'Market and demand metrics for portfolio operations.'),
    ('pricing_metrics', 'Pricing Metrics', 'communication', 'Pricing, occupancy, usage, and subscription metrics.'),
    ('survey_results', 'Survey Results', 'communication', 'Survey responses and completion metrics.')
)
insert into public.report_definitions (
  id,
  slug,
  name,
  category,
  description,
  parameter_schema,
  default_filters,
  output_formats,
  is_system,
  active
)
select
  gen_random_uuid(),
  slug,
  name,
  category::report_category,
  description,
  '{}'::jsonb,
  '{}'::jsonb,
  array['pdf', 'xlsx', 'csv']::report_format[],
  true,
  true
from catalog
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  parameter_schema = coalesce(public.report_definitions.parameter_schema, '{}'::jsonb),
  default_filters = coalesce(public.report_definitions.default_filters, '{}'::jsonb),
  output_formats = excluded.output_formats,
  is_system = true,
  active = true,
  updated_at = now();
